import React from 'react';
import SEO from '../components/SEO';
import { Shield, Lock, Eye, Database, Globe, UserCheck, Bell, Mail, Info } from 'lucide-react';
import '../styles/legal.css';

const PrivacyPolicy = () => {
    return (
        <div className="legal-page-layout">
            <SEO 
                title="Privacy Policy | Deenova Learning Hub" 
                description="Learn about how we collect, safeguard and disclose information that results from your use of our Service."
            />
            
            
            <header className="legal-header">
                <div className="container">
                    <h1 className="text-white">Privacy Policy</h1>
                    <p className="text-white">Effective date: 2024</p>
                </div>
            </header>

            <main className="legal-content-section">
                <div className="container">
                    <div className="legal-grid">
                        <aside className="legal-sidebar">
                            <div className="toc-card">
                                <h3>Table of Contents</h3>
                                <nav className="toc-nav">
                                    <a href="#introduction" className="toc-link"><Info size={16} /> 1. Introduction</a>
                                    <a href="#definitions" className="toc-link"><Database size={16} /> 2. Definitions</a>
                                    <a href="#cookies" className="toc-link"><Bell size={16} /> 3. Cookie Policy</a>
                                    <a href="#collection" className="toc-link"><Eye size={16} /> 4. Data Collection</a>
                                    <a href="#usage" className="toc-link"><Lock size={16} /> 5. Use of Data</a>
                                    <a href="#transfer" className="toc-link"><Globe size={16} /> 6. Data Transfer</a>
                                    <a href="#rights" className="toc-link"><UserCheck size={16} /> 7. Your Rights</a>
                                    <a href="#contact" className="toc-link"><Mail size={16} /> 8. Contact Us</a>
                                </nav>
                            </div>
                        </aside>

                        <div className="legal-card">
                            <section className="legal-section" id="introduction">
                                <div className="section-title">
                                    <Info size={20} />
                                    <h2>1. Introduction</h2>
                                </div>
                                <p>
                                    Welcome to Deenova Learning Hub. We operate as an online educational platform (the "Service") and are committed to protecting your personal data.
                                </p>
                                <p>
                                    Our Privacy Policy governs your visit to our platform and explains how we collect, safeguard, and disclose information resulting from your use of our Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
                                </p>
                            </section>

                            <section className="legal-section" id="definitions">
                                <div className="section-title">
                                    <Database size={20} />
                                    <h2>2. Definitions</h2>
                                </div>
                                <p><strong>PERSONAL DATA:</strong> Data about a living individual who can be identified from those data.</p>
                                <p><strong>USAGE DATA:</strong> Data collected automatically either generated by the use of Service or from Service infrastructure itself.</p>
                                <p><strong>COOKIES:</strong> Small files stored on your device (computer or mobile device).</p>
                                <p><strong>DATA CONTROLLER:</strong> The entity which determines the purposes for which and the manner in which any personal data are processed.</p>
                            </section>

                            <section className="legal-section" id="cookies">
                                <div className="section-title">
                                    <Bell size={20} />
                                    <h2>3. Cookie Policy</h2>
                                </div>
                                <p>
                                    We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier.
                                </p>
                                <p>Examples of Cookies we use:</p>
                                <ul>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
                                </ul>
                            </section>

                            <section className="legal-section" id="collection">
                                <div className="section-title">
                                    <Eye size={20} />
                                    <h2>4. Information Collection and Use</h2>
                                </div>
                                <p>
                                    While using our Service, we may ask you to provide us with certain personally identifiable information ("Personal Data") such as:
                                </p>
                                <ul>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}>Email address</li>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}>First name and last name</li>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}>Phone number</li>
                                    <li style={{marginLeft: '35px', color: 'var(--text-muted)', marginBottom: '0.5rem'}}>Address, State, Province, ZIP/Postal code, City</li>
                                </ul>
                                <p>
                                    We also collect Usage Data automatically, including your IP address, browser type, and time spent on our pages.
                                </p>
                            </section>

                            <section className="legal-section" id="usage">
                                <div className="section-title">
                                    <Lock size={20} />
                                    <h2>5. Use of Data</h2>
                                </div>
                                <p>Deenova Learning Hub uses the collected data for various purposes:</p>
                                <p>- To provide and maintain our Service</p>
                                <p>- To notify you about changes to our Service</p>
                                <p>- To provide customer support</p>
                                <p>- To monitor the usage of our Service and detect technical issues</p>
                                <p>- To provide you with news and special offers</p>
                            </section>

                            <section className="legal-section" id="transfer">
                                <div className="section-title">
                                    <Globe size={20} />
                                    <h2>6. Transfer of Data</h2>
                                </div>
                                <p>
                                    Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your jurisdiction. If you are located outside Pakistan and choose to provide information to us, please note that we transfer the data to Pakistan and process it there.
                                </p>
                                <p>
                                    We take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy.
                                </p>
                            </section>

                            <section className="legal-section" id="rights">
                                <div className="section-title">
                                    <UserCheck size={20} />
                                    <h2>7. Your Data Protection Rights</h2>
                                </div>
                                <p>
                                    Depending on your location, you may have rights under GDPR, CalOPPA, or CCPA. These include the right to access, update, or delete the information we have on you, as well as the right to object to or restrict processing.
                                </p>
                                <p>
                                    If you wish to be informed what Personal Data we hold about you or want it removed, please contact us at team@altacademy.org.
                                </p>
                            </section>

                            <section className="legal-section" id="contact">
                                <div className="section-title">
                                    <Mail size={20} />
                                    <h2>8. Contact Us</h2>
                                </div>
                                <p>
                                    If you have any questions about this Privacy Policy, please contact us:
                                </p>
                                <p>
                                    <strong>Email:</strong> team@altacademy.org <br />
                                    <strong>Address:</strong> Suite no 31, 50 C, Lane 2, Zulfiqar & Al Murtaza Commercial Area, DHA Phase 8, Karachi, Pakistan.
                                </p>
                            </section>

                            <div className="legal-footer">
                                <p>Copyright &copy; 2026 Deenova Learning Hub. All rights reserved.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};

export default PrivacyPolicy;
